// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import PasswordAuthenticationConcept from "./PasswordAuthentication/PasswordAuthenticationConcept.ts";
import FileUploadingConcept from "./FileUploading/FileUploadingConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SessioningConcept from "./Sessioning/SessioningConcept.ts";
import SharedGoalsConcept from "./SharedGoals/SharedGoalsConcept.ts";
import UserProfileConcept from "./UserProfile/UserProfileConcept.ts";
import EmailVerificationConcept from "./EmailVerification/EmailVerificationConcept.ts";

export type { default as PasswordAuthenticationConcept } from "./PasswordAuthentication/PasswordAuthenticationConcept.ts";
export type { default as FileUploadingConcept } from "./FileUploading/FileUploadingConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SessioningConcept } from "./Sessioning/SessioningConcept.ts";
export type { default as SharedGoalsConcept } from "./SharedGoals/SharedGoalsConcept.ts";
export type { default as UserProfileConcept } from "./UserProfile/UserProfileConcept.ts";
export type { default as EmailVerificationConcept } from "./EmailVerification/EmailVerificationConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const PasswordAuthentication = Engine.instrumentConcept(new PasswordAuthenticationConcept(db));
export const FileUploading = Engine.instrumentConcept(new FileUploadingConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Sessioning = Engine.instrumentConcept(new SessioningConcept(db));
export const SharedGoals = Engine.instrumentConcept(new SharedGoalsConcept(db));
export const UserProfile = Engine.instrumentConcept(new UserProfileConcept(db));
export const EmailVerification = Engine.instrumentConcept(new EmailVerificationConcept(db));
