import { Collection, Database } from "@deps/mongo";
import { Empty, ID } from "@utils/types.ts";
import { GeminiLLM } from "@utils/gemini-llm.ts";

const USER_PROFILE_COLLECTION = "Userprofile.userProfiles";

// Types for this concept
type User = ID;
type SharedGoal = ID;
type SharedStep = ID;

interface SharedGoalDoc {
  _id: SharedGoal;
  users: User[]; // Set of users sharing the goal
  description: string;
  isActive: boolean;
  createdAt: Date;
  closedAt?: Date;
}

interface SharedStepDoc {
  _id: SharedStep;
  sharedGoalId: SharedGoal;
  description: string;
  completion?: Date;
}

/**
 * @concept SharedGoals
 */
export default class SharedGoalsConcept {
  private sharedGoals: Collection<SharedGoalDoc>;
  private sharedSteps: Collection<SharedStepDoc>;
  private sharedGoalsInstance: Collection<{ groupKey: string; users: User[]; isInitialized: boolean }>;
  private llm: GeminiLLM | null = null;
  private apiKey: string | null = null;

  constructor(private readonly db: Database, apiKey?: string) {
    this.sharedGoals = this.db.collection<SharedGoalDoc>("SharedGoals.sharedGoals");
    this.sharedSteps = this.db.collection<SharedStepDoc>("SharedGoals.sharedSteps");
    this.sharedGoalsInstance = this.db.collection<{ groupKey: string; users: User[]; isInitialized: boolean }>("SharedGoals.sharedGoalsInstance");
    this.apiKey = apiKey || Deno.env.get("GEMINI_API_KEY") || null;
    if (this.apiKey) {
      this.initializeLLM(this.apiKey);
    }
  }

  /**
   * Initializes the Gemini LLM with the provided API key.
   *
   * @param apiKey - Gemini API key string.
   */
  initializeLLM(apiKey: string): void {
    try {
      this.llm = new GeminiLLM({ apiKey });
    } catch (error) {
      console.warn("Failed to initialize LLM:", error);
      this.llm = null;
    }
  }

  /**
   * Validates the quality and structure of steps generated by the LLM.
   *
   * @param steps - Array of step descriptions.
   * @returns Error message if validation fails, otherwise undefined.
   */
  private validateStepQuality(steps: string[]): string | undefined {
    for (const step of steps) {
      if (step.length < 10) {
        return `Step too brief: "${step}". Provide more detail to clarify the action.`;
      }
      if (step.length > 300) {
        return `Step too detailed: "${step}". Keep each step brief and focused on one main action.`;
      }
    }
    const vagueWords = ["etc", "maybe", "possibly", "as necessary"];
    for (const step of steps) {
      for (const word of vagueWords) {
        const re = new RegExp(`\\b${word.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&")}\\b`, "i");
        if (re.test(step)) {
          return `Vague step detected: "${step}". Steps must be specific and actionable.`;
        }
      }
    }
    for (const step of steps) {
      const commaCount = (step.match(/,/g) || []).length;
      if (commaCount > 6) {
        return `Step too verbose: "${step}". Break into simpler steps.`;
      }
    }
    return undefined;
  }

  /**
   * Generates a deterministic group key from a list of users.
   *
   * @param users - Array of user IDs.
   * @returns A string key representing the group.
   */
  private static groupKey(users: User[]): string {
    return users.slice().sort().join("|");
  }

  /**
   * Creates a new shared goal for a set of users.
   *
   * @param users - Array of user IDs.
   * @param description - Description of the shared goal.
   * @returns The ID of the created shared goal, or an error.
   */
  async createSharedGoal({ users, description }: { users: User[]; description: string }): Promise<{ sharedGoalId: SharedGoal } | { error: string }> {
    if (!description || users.length < 2) {
      return { error: "Description must not be empty and/or at least two users required." };
    }
    // Check for existing active goal with same users and description
    const existing = await this.sharedGoals.findOne({
      users: { $all: users, $size: users.length },
      description,
      isActive: true,
    });
    if (existing) {
      return { error: "Active shared goal with these users and description already exists." };
    }
    const _id = crypto.randomUUID() as SharedGoal;
    await this.sharedGoals.insertOne({ _id, users, description, isActive: true, createdAt: new Date() });
    return { sharedGoalId: _id };
  }

  /**
   * Uses Gemini LLM to generate steps for a shared goal.
   *
   * @param sharedGoal - The shared goal ID.
   * @param user - The user requesting step generation.
   * @returns Array of generated step documents, or an error.
   */
  async generateSharedSteps({ sharedGoal, user }: { sharedGoal: SharedGoal; user: User }): Promise<{ steps: SharedStepDoc[] } | { error: string }> {
    const goal = await this.sharedGoals.findOne({ _id: sharedGoal, isActive: true });
    if (!goal || !goal.users.includes(user)) {
      return { error: "Shared goal not found or user not a member." };
    }
    const existingSteps = await this.sharedSteps.find({ sharedGoalId: sharedGoal }).toArray();
    if (existingSteps.length > 0) {
      return { error: "Shared steps already exist for this goal." };
    }
    if (!this.llm) {
      return { error: "LLM not initialized. API key might be missing or invalid." };
    }
    // LLM prompt
    const llmPrompt = [
      'You are a helpful AI assistant that creates a recommended plan of clear steps',
      'for a set of people working together on a shared goal.',
      '',
      `Shared goal description: "${goal.description}"`,
      '',
      'Response Requirements:',
      '1. Return ONLY a single-line JSON array of strings',
      '2. Each string should be a specific, complete, measurable, and actionable step',
      '3. Steps must be relevant to the shared goal and feasible for an average group (not overly ambitious or vague)',
      '4. Only contain necessary steps to achieve the goal, avoid filler steps and be mindful of number of steps generated',
      '5. Steps must be in logical order',
      '6. Do NOT use line breaks or extra whitespace',
      '7. Properly escape any quotes in the text',
      '8. No step numbers or prefixes',
      '9. No comments or explanations',
      '',
      'Example response format:',
      '["Define the shared objective","Break down the goal into actionable steps","Assign responsibilities among users"]',
      '',
      'Return ONLY the JSON array, nothing else.'
    ].join('\n');
    let responseText: string;
    try {
      responseText = await this.llm.executeLLM(llmPrompt);
    } catch (e) {
      return { error: `Failed to call LLM: ${e instanceof Error ? e.message : String(e)}` };
    }
    let stepDescriptions: string[];
    try {
      stepDescriptions = JSON.parse(responseText);
    } catch (_parseError) {
      return { error: "Failed to parse LLM response as JSON array." };
    }
    if (!Array.isArray(stepDescriptions) || stepDescriptions.some((d) => typeof d !== "string")) {
      return { error: "LLM returned invalid step format. Expected a JSON array of strings." };
    }
    const validationError = this.validateStepQuality(stepDescriptions);
    if (validationError) {
      return { error: validationError };
    }
    const steps: SharedStepDoc[] = stepDescriptions.map((desc) => ({
      _id: crypto.randomUUID() as SharedStep,
      sharedGoalId: sharedGoal,
      description: desc.trim(),
    }));
    if (steps.length > 0) {
      await this.sharedSteps.insertMany(steps);
    }
    return { steps };
  }

  /**
   * Regenerates steps for a shared goal by deleting existing steps and generating new ones.
   *
   * @param sharedGoal - The shared goal ID.
   * @param user - The user requesting regeneration.
   * @returns Array of generated step documents, or an error.
   */
  async regenerateSharedSteps({ sharedGoal, user }: { sharedGoal: SharedGoal; user: User }): Promise<{ steps: SharedStepDoc[] } | { error: string }> {
    const goal = await this.sharedGoals.findOne({ _id: sharedGoal, isActive: true });
    if (!goal || !goal.users.includes(user)) {
      return { error: "Shared goal not found or user not a member." };
    }
    await this.sharedSteps.deleteMany({ sharedGoalId: sharedGoal });
    return this.generateSharedSteps({ sharedGoal, user });
  }

  /**
   * Adds a new step to a shared goal.
   *
   * @param sharedGoal - The shared goal ID.
   * @param description - Description of the step.
   * @param user - The user adding the step.
   * @returns The created step document, or an error.
   */
  async addSharedStep({ sharedGoal, description, user }: { sharedGoal: SharedGoal; description: string; user: User }): Promise<{ step: SharedStepDoc } | { error: string }> {
    const goal = await this.sharedGoals.findOne({ _id: sharedGoal, isActive: true });
    if (!goal || !goal.users.includes(user)) {
      return { error: "Shared goal not found or user not a member." };
    }
    if (!description) {
      return { error: "Description must not be empty." };
    }
    const step: SharedStepDoc = {
      _id: crypto.randomUUID() as SharedStep,
      sharedGoalId: sharedGoal,
      description,
    };
    await this.sharedSteps.insertOne(step);
    return { step };
  }

  /**
   * Marks a shared step as completed.
   *
   * @param step - The shared step ID.
   * @param user - The user completing the step.
   * @returns Empty object on success, or an error.
   */
  async completeSharedStep({ step, user }: { step: SharedStep; user: User }): Promise<Empty | { error: string }> {
    const stepDoc = await this.sharedSteps.findOne({ _id: step });
    if (!stepDoc) return { error: "Step not found." };
    const goal = await this.sharedGoals.findOne({ _id: stepDoc.sharedGoalId, isActive: true });
    if (!goal || !goal.users.includes(user)) return { error: "Shared goal not found or user not a member." };
    if (stepDoc.completion) return { error: "Step already completed." };
    await this.sharedSteps.updateOne({ _id: step }, { $set: { completion: new Date() } });
    return {};
  }

  /**
   * Removes a shared step from a goal.
   *
   * @param step - The shared step ID.
   * @param user - The user removing the step.
   * @returns Empty object on success, or an error.
   */
  async removeSharedStep({ step, user }: { step: SharedStep; user: User }): Promise<Empty | { error: string }> {
    const stepDoc = await this.sharedSteps.findOne({ _id: step });
    if (!stepDoc) return { error: "Step not found." };
    const goal = await this.sharedGoals.findOne({ _id: stepDoc.sharedGoalId, isActive: true });
    if (!goal || !goal.users.includes(user)) return { error: "Shared goal not found or user not a member." };
    if (stepDoc.completion) return { error: "Cannot remove a completed step." };
    await this.sharedSteps.deleteOne({ _id: step });
    return {};
  }

  /**
   * Closes a shared goal, marking it inactive and setting closedAt.
   *
   * @param sharedGoal - The shared goal ID.
   * @param user - The user closing the goal.
   * @returns Empty object on success, or an error.
   */
  async closeSharedGoal({ sharedGoal, user }: { sharedGoal: SharedGoal; user: User }): Promise<Empty | { error: string }> {
    const goal = await this.sharedGoals.findOne({ _id: sharedGoal, isActive: true });
    if (!goal || !goal.users.includes(user)) return { error: "Shared goal not found or user not a member." };
    await this.sharedGoals.updateOne({ _id: sharedGoal }, { $set: { isActive: false, closedAt: new Date() } });
    return {};
  }


  /**
   * Sets the isInitialized flag for the shared goals instance (group of users).
   *
   * @param users - Array of user IDs.
   * @param isInitialized - Boolean flag for initialization.
   * @returns Empty object.
   */
  async setInitialized({ users, isInitialized }: { users: User[]; isInitialized: boolean }): Promise<Empty> {
    const groupKey = SharedGoalsConcept.groupKey(users);
    await this.sharedGoalsInstance.updateOne(
      { groupKey },
      { $set: { isInitialized, users, groupKey } },
      { upsert: true },
    );
    return {};
  }

  /**
   * Returns all shared goals that include the given user.
   *
   * @param user - The user ID.
   * @returns Array of shared goal documents with user display names.
   */
  async _getAllGoalsForUser({ user }: { user: User }): Promise<Array<Omit<SharedGoalDoc, "users"> & { users: { id: User; displayname: string }[] }>> {
    const goals = await this.sharedGoals.find({ users: user }).toArray();
    // Gather all unique user IDs from all goals
    const allUserIds = [...new Set(goals.flatMap(g => g.users))].map(String); // ensure string[]
    // Fetch displaynames from UserProfile.userProfiles
    const profilesCollection = this.db.collection<{ _id: string; displayname?: string }>(USER_PROFILE_COLLECTION);
    const profileDocs = await profilesCollection.find({ _id: { $in: allUserIds } }).toArray();
    const userMapLocal = Object.fromEntries(profileDocs.map(u => [u._id, u.displayname]));
    // Map users in each goal to { id, displayname }
    return goals.map(g => {
      const { _id, description, isActive, createdAt, closedAt } = g;
      const base = {
        _id,
        description,
        isActive,
        createdAt,
        users: g.users.map(u => ({ id: u, displayname: userMapLocal[String(u)] || String(u) }))
      };
      return closedAt ? { ...base, closedAt } : base;
    });
  }

  /**
   * Returns all shared goals for a set of users, optionally filtered by active status.
   *
   * @param users - Array of user IDs.
   * @param isActive - Optional boolean to filter by active status.
   * @returns Array of shared goal documents.
   */
  async _getSharedGoals({ users, isActive }: { users: User[]; isActive?: boolean }): Promise<{ id: SharedGoal; description: string; isActive: boolean; createdAt: Date; closedAt?: Date; users: User[] }[]> {
    const query: Record<string, unknown> = { users: { $all: users, $size: users.length } };
    if (typeof isActive === "boolean") query.isActive = isActive;
    const goals = await this.sharedGoals.find(query).toArray();
    return goals.map(g => {
      const { _id, description, isActive, createdAt, closedAt, users } = g;
      const base = { id: _id, description, isActive, createdAt, users };
      return closedAt ? { ...base, closedAt } : base;
    });
  }

  /**
   * Returns a shared goal by ID for a set of users.
   *
   * @param users - Array of user IDs.
   * @param sharedGoalId - The shared goal ID.
   * @returns Shared goal document or null if not found.
   */
  async _getSharedGoalById({ users, sharedGoalId }: { users: User[]; sharedGoalId: SharedGoal }): Promise<{ id: SharedGoal; description: string; isActive: boolean; createdAt: Date; closedAt?: Date; users: User[] } | null> {
    const goal = await this.sharedGoals.findOne({ _id: sharedGoalId, users: { $all: users, $size: users.length } });
    if (!goal) return null;
    return {
      id: goal._id,
      description: goal.description,
      isActive: goal.isActive,
      createdAt: goal.createdAt,
      closedAt: goal.closedAt,
      users: goal.users
    };
  }

  /**
   * Returns all steps for a shared goal.
   *
   * @param sharedGoal - The shared goal ID.
   * @returns Array of step documents.
   */
  async _getSharedSteps({ sharedGoal }: { sharedGoal: SharedGoal }): Promise<{ id: SharedStep; description: string; completion?: Date }[]> {
    const steps = await this.sharedSteps.find({ sharedGoalId: sharedGoal }).toArray();
    return steps.map(s => ({ id: s._id, description: s.description, completion: s.completion }));
  }
}
