// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_emailVerification from "./emailVerification.sync.ts";
import * as sync_sample from "./sample.sync.ts";
import * as sync_profile from "./profile.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_emailVerification)) {
  if (typeof func === "function") {
    allSyncs[`emailVerification.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_sample)) {
  if (typeof func === "function") {
    allSyncs[`sample.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_profile)) {
  if (typeof func === "function") {
    allSyncs[`profile.${name}`] = func as Sync;
  }
}

export default allSyncs;
